export const ORG_CATEGORIES = [
  "professional_sports",
  "minor_league_baseball",
  "ncaa_university",
  "college",
  "community_college",
  "high_school",
  "athletic_department",
  "school_district",
  "nonprofit_501c3",
  "hospital_foundation",
  "community_foundation",
  "museum",
  "zoo",
  "church",
  "chamber_of_commerce",
  "convention_center",
  "fairground",
  "county_calendar",
  "city_calendar",
  "community_organization",
  "other",
] as const;

export type OrgCategory = (typeof ORG_CATEGORIES)[number];

export const ORG_CATEGORY_LABELS: Record<OrgCategory, string> = {
  professional_sports: "Professional Sports Team",
  minor_league_baseball: "Minor League Baseball",
  ncaa_university: "NCAA University",
  college: "College",
  community_college: "Community College",
  high_school: "High School",
  athletic_department: "Athletic Department",
  school_district: "School District",
  nonprofit_501c3: "501(c)(3) Organization",
  hospital_foundation: "Hospital Foundation",
  community_foundation: "Community Foundation",
  museum: "Museum",
  zoo: "Zoo",
  church: "Church",
  chamber_of_commerce: "Chamber of Commerce",
  convention_center: "Convention Center",
  fairground: "Fairground",
  county_calendar: "County Event Calendar",
  city_calendar: "City Event Calendar",
  community_organization: "Community Organization",
  other: "Other",
};
